spring:
  application:
    name: reservation-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/reservation_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic:
      reservation-created: reservation-created


server:
  port: 8081

logging:
  level:
    org.springframework: INFO
    com.hotel: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# OpenAPI Info
openapi:
  info:
    title: Reservation Service API
    description: API for managing hotel reservations
    version: 1.0.0
    contact:
      name: Reservation Service Team
      email: reservation@example.com
