spring:
  application:
    name: reservation-service
  datasource:
    url: jdbc:postgresql://localhost:5433/reservation_service
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      reservation-created: reservation-created


server:
  port: 8081

logging:
  level:
    org.springframework: INFO
    com.hotel: DEBUG