spring:
  application:
    name: oteller
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/hotel_service}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

server:
  port: 8080

logging:
  level:
    org.springframework: INFO
    com.hotel: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha

# OpenAPI Info
openapi:
  info:
    title: Hotel Service API
    description: API for managing hotels and rooms
    version: 1.0.0
    contact:
      name: Hotel Service Team
      email: hotel@example.com
